---
title: "figures-code"
author: "Zach Bengtsson"
date: "3/12/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, echo=FALSE}
library(magrittr)
library(ggplot2)
install.packages("ggtext")
library(ggtext)

siscowet <- read.csv("~/Desktop/github/Assignment-5/data/siscowet.csv")
```

```{r weightvslength}
 siscowet %>%
        ggplot(aes(x=len,y=wgt)) +
        geom_point()
```
```{r lenvswgtlm}
siscowet %>%
        ggplot(aes(x=len,
                   y=wgt,
                   color=locID)) +
        geom_point() + 
        ylab("Weight (g)") + 
        xlab("Total length (mm)") + 
        labs(color="Location",
             title = "<b> Fish weight increases with length</b><br>") +
        theme_minimal() + 
        theme(
                plot.title.position = "plot",
                  plot.title = element_textbox_simple(size=12),
                axis.title.y = element_text(angle = 0, vjust = 0.5,size=14),
              axis.text = element_text(size=12),
              legend.position = "none") + 
          geom_smooth(method = "lm", se = FALSE)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
